### ISSUE TITLE
CORS policy for sandbox

### ISSUE THREAD

**Issue by naulacambra** [SignRequest/signrequest-node-client#1]
Hello,

We recently purchased a license for your platform, and are testing your API testing environment to integrate your services with our in-house software.

I've tried something quite simple, create a document, but I face a CORS problem.

`Access to XMLHttpRequest at 'https://my-company.signrequest.com/api/v1/documents/' from origin 'http://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

From what I understand, there should be some place on the dashboard where you can set the allowed origins, right? Or am I missing something?

This is my code

``` js
import SignRequestClient from "signrequest-client";

var client = SignRequestClient.ApiClient.instance;
var client.basePath = "https://my-company.signrequest.com/api/v1";

// Configure API key authorization: Token
var Token = client.authentications["Token"];
Token.apiKey = "my-token";
Token.apiKeyPrefix = "Token";

var documentApi = new SignRequestClient.DocumentsApi(client);

var example_pdf_url = "http://africau.edu/images/default/sample.pdf";
var document = new SignRequestClient.Document();
document.file_from_url = example_pdf_url ;

documentApi.documentsCreate(document, (error, data, response) => {
   // ERROR
});
```

**Comment by michi88** [comment]
We're having a look and get back to you asap.

**Comment by michi88** [comment]
Btw, this library is intended for backend use only, you shouldn't run it in a browser (that would also leak your Token). Apart from that, there is an issue when installing this client as noted by you as well. We're fixing this.

**Comment by naulacambra** [comment]
Ok, thank you. 

There is any package for frontend usage?

**Comment by cjackson** [comment]
@naulacambra We do not have a package that is intended for frontend use. As @michi88 mentions, there's no way of doing this without leaking your token.
