### ISSUE TITLE
double callback bug

### ISSUE THREAD

**Issue by jm06487** [SignRequest/signrequest-node-client#4]
Just started getting this error...

Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises
Warning: .end() was called twice. This is not supported in superagent
superagent: double callback bug

SyntaxError: Unexpected token { in JSON at position 2448

**Comment by Archivolt1** [comment]
I am also having this same issue with the code below at .documentsCreate():

        const signrequestClient = require('signrequest-client');
        signrequestClient.ApiClient.instance.authentications['Token'].apiKey = process.env.SIGNREQUEST_TOKEN;

`

        // Create SignRequest Document from args.fileUrl
        const docsApi = await new context.signrequestClient.DocumentsApi();
        let documentData = await new context.signrequestClient.Document();
        documentData.file_from_url = args.fileUrl;
        let requestData = await new context.signrequestClient.SignRequest();
        try {
          await docsApi.documentsCreate(documentData, async function (error, data, response) {
            if (error) {
              throw new Error(error);
            } else {
            }
          });
        } catch (e) {
          return new Error(e);
        }

`

Above looks OK? I am on Superagent 5. The warnings look to be caused by Superagent but the error appears to be a parsing error of some sort of payload or response.

**Comment by cjackson** [comment]
Unfortunately using async / await with `documentsCreate` doesn't work, because it's calling `.end()` in order to facilitate the callback (see: https://github.com/SignRequest/signrequest-node-client/blob/v1.1.0/src/ApiClient.js#L477-L494).

To get around this, you could wrap it with your own promise. Something like this:

```js
function documentCreate() {
  const docsApi = new SignrequestClient.DocumentsApi();
  let documentData = new SignrequestClient.Document();
  documentData.file_from_url = 'https://ddocs.google.com/document/d/1oI2R1SxfMNZXiz3jCQvorpoklF9xq_dCJnOpkI-zo80/edit?usp=sharing';
  return new Promise((resolve, reject) => {
    try {
      docsApi.documentsCreate(documentData, function (error, data, response) {
        if (error) {
          reject(new Error(error));
        } else {
          resolve(data);
        }
      });
    } catch (e) {
      reject(new Error(e));
    }
  })
}

async function testDocumentCreate() {
  const document = await documentCreate();

  console.log('document', document);
}

testDocumentCreate();
```

**Comment by Archivolt1** [comment]
Ok, thanks for the information! Works perfectly!
